### ISSUE TITLE
Add .def file

### ISSUE THREAD

**Issue by yutannihilation** [yutannihilation/savvy#110]
Just hit https://github.com/extendr/rextendr/issues/211

**Comment by yutannihilation** [comment]
This is the convention.

> Under Windows you can supply an exports definitions file called dllname-win.def: otherwise all entry points in objects (but not libraries) supplied to R CMD SHLIB will be exported from the DLL.

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Creating-shared-objects

**Comment by sounkou-bioinfo** [comment]
thank you for this issue ! i ve hit here too with [cgo](https://github.com/sounkou-bioinfo/goServeR/blob/main/src/goserveR-win.def) and your template solved it !
