### ISSUE TITLE
Support specifying a user-defined struct as the return type properly

### ISSUE THREAD

**Issue by yutannihilation** [yutannihilation/savvy#116]
Currently, the user-defined struct can be created by `new()` method of the struct. However, one might want to

```rust
#[savvy]
impl Person {
    fn new() -> Self {
        Self {
            name: "".to_string(),
        }
    }

    fn new2() -> Self {
        Self {
            name: "".to_string(),
        }
    }

    // ..snip..
}

#[savvy]
fn new_external() -> savvy::Result<Person> {
    // ..snip..
}

```

**Comment by yutannihilation** [comment]
Probably, allowing this is too complex,

```rust
#[savvy]
fn new_external() -> savvy::Result<Person> {
    // ..snip..
}
```

and this is already possible, while the function name is a bit tricky (`Person_new2()`).

```rust
#[savvy]
impl Person {
    fn new2() -> Self {
        Self {
            name: "".to_string(),
        }
    }

    // ..snip..
}
```

Closing for now.

**Comment by yutannihilation** [comment]
Something like this needs to be supported.

```rust
#[savvy]
impl DataFrame {
    fn group_by(&mut self, by: StringSexp) -> savvy::Result<GroupBy> {
        self.group_by(by.iter())
    }
}
```

**Comment by yutannihilation** [comment]
> having the names of my functions changed

What do you mean? Like `Person_new2`? It's unrelated to the return type.

**Comment by daniellga** [comment]
I was talking about this:

```
If you define a constructor with a different name than new(), the correspopnding R function is <type_name>_<method>. For example, the method below will be available as Person_new_with_name() on R's side.
```

Sorry for the lack of context. I thought you were doing this change only when returning `Self`.

**Comment by yutannihilation** [comment]
It's status quo. Methods needs to such a prefix as `Person_` to avoid the conflict. But, it's a good point, thanks.

What R function do you expect for this? Simply `new2()`? `Person$new2()`? Or something else?

```rust
#[savvy]
impl Person {
    fn new2() -> Self {
        Self {
            name: "".to_string(),
        }
    }

    // ..snip..
}
```

**Comment by daniellga** [comment]
I am ok with both `Person$new` and `Person_new`. Although the first choice seems more natural for me (it separates the method name), I don't know if it's because I am used to extendr.
I saw a `Person()` constructor when there is a method called `new`... Would `Person$new` or `Person_new` also be available at the same time?

**Comment by yutannihilation** [comment]
> I saw a `Person()` constructor when there is a method called `new`...

Yeah, I thought the convention is nice and simple if the struct needs only one constructor, which I expected is the most of the cases. But, now I found more complex cases so I'm no longer confident about this design.

> Would `Person$new` or `Person_new` also be available at the same time?

If I add `Person$new()`, `Person()` will be gone. `Person_new()` is available probably in some form like below, though it's not intended to be used by users.

```r
Person <- list(
  new = Person_new
)

Person_new <- function() {
  ...
}
```

**Comment by daniellga** [comment]
I mean I think it is a little weird if I have let's say 3 constructors and only one of them (`new`) is called in a different manner.

**Comment by yutannihilation** [comment]
Thanks. To the end users, there's only one constructor, either `Person$new()` or `Person()`. `Person_new()` is not exported.

**Comment by yutannihilation** [comment]
A small correction. Now there's only `Person$new()`. No `Person_new()` is defined because the generated code after #117 is like this:

```r
#' A person with a name
#'
#' @export
Person <- new.env(parent = emptyenv())
Person$new <- function() {
  .savvy_wrap_Person(.Call(Person_new__impl))
}
```
