### ISSUE TITLE
Return type from an `impl` block

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#136]
The `impl` block only lets me return `Self`, not the type itself.

Example:
```
#[savvy]
impl HArray {
    fn new_from_values(arr: Sexp, dtype: &HDataType) -> HArray {
```
And it also gives the wrong error below (it should also consider `Self` as returning type)
```
 the return type must be savvy::Result<T> or savvy::Result<()>
 ```
 
 While this works:
 
```
#[savvy]
impl HArray {
    fn new_from_values(arr: Sexp, dtype: &HDataType) -> Self {
```

**Comment by yutannihilation** [comment]
Sorry, that's intended. `Self` is an exception. The return type should only be `savvy::Result<>`. Actually, I was wondering if `Self` should be disallowed (I mean, `savvy::Result<Self>`).

**Comment by daniellga** [comment]
imo, no problem if you only want to return `Result` (although I don't see a reason to do it). But the way it is right now is a little weird since `Self` should be the same as `HArray` in this case.

**Comment by yutannihilation** [comment]
Hm, okay, let me try it. If it's not so difficult, I'll implement it.

> although I don't see a reason to do it

For simplicity. Adding more syntax means it needs more code and more test cases. Please feel free to ask whatever feature, but I'm aware my bandwidth is very limited.

**Comment by daniellga** [comment]
you can return `Result` only. It would be fine.

**Comment by yutannihilation** [comment]
Closed via https://github.com/yutannihilation/savvy/commit/e6e3a3cd2d1032b72794936cf4b0d20da58f8665

**Comment by yutannihilation** [comment]
Thanks. I'm still wondering it, but let's not remove `Self` this time.
