### ISSUE TITLE
savvy-cli maybe parsing files it shouldn't

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#147]
First time I actually tried running `savvy-cli update` and it parsed files that were commented out in `lib.rs`. Is it supposed to happen?

```
Parsing ./src/rust/src/conversions.rs
Parsing ./src/rust/src/harray.rs
Parsing ./src/rust/src/harrayr.rs
Parsing ./src/rust/src/haudioop.rs
Parsing ./src/rust/src/haudiosink.rs
Parsing ./src/rust/src/hdatatype.rs
Parsing ./src/rust/src/hfft.rs
Parsing ./src/rust/src/hfile.rs
Parsing ./src/rust/src/hmetadatatype.rs
Parsing ./src/rust/src/hpolynomialdegree.rs
Parsing ./src/rust/src/hresampler.rs
Parsing ./src/rust/src/hresamplertype.rs
Parsing ./src/rust/src/hsincinterpolationparams.rs
Parsing ./src/rust/src/hwindow.rs
Parsing ./src/rust/src/lib.rs
Parsing ./src/rust/src/partialeq.rs
Parsing ./src/rust/src/r_docs.rs
Writing ./src/rust/api.h
Writing ./src/init.c
Writing ./R/wrappers.R
```

lib.rs
```rs
//mod conversions;
mod harray;
mod harrayr;
mod haudioop;
//mod haudiosink;
mod hdatatype;
mod hfft;
//mod hfile;
mod hmetadatatype;
mod hpolynomialdegree;
//mod hresampler;
mod hresamplertype;
mod hsincinterpolationparams;
mod hwindow;
mod partialeq;
//mod r_docs;
```

If this is intended, how do I make a file to be ignored by savvy without removing it?

**Comment by yutannihilation** [comment]
Aw, sorry... I didn't expext anyone would hit this problem this early! Yes, currently this is a limitaton because what savvy-cli does is static analysis and it's not easy to mimick the rule.

**Comment by yutannihilation** [comment]
I think `savvy-cli` now can handle your case as expected. Note that, ultimately, what `savvy-cli` does is static analysis, which cannot be perfectly in line with what the Rust compiler actually does. For example, it cannot handle `#[cfg(...)]` because evaluating it manually is almost impossible. 

Anyway, please use the new binary (v0.4.2), which will be released shortly.
