### ISSUE TITLE
windows compilation fails

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#155]
I am having some compilation error on windows trying to execute your [guide](https://yutannihilation.github.io/savvy/guide/01_get_started.html). This error occurs when doing `devtools::document()`.

![image](https://github.com/yutannihilation/savvy/assets/43149605/3b14e4fd-8511-49a9-88db-fb751fc94d38)

![image](https://github.com/yutannihilation/savvy/assets/43149605/47a77bfe-6211-4f29-84fe-75ac25b69eac)

![image](https://github.com/yutannihilation/savvy/assets/43149605/fc7c9675-6999-40da-92d7-a4f0e98ad55b)

Please let me know if you need more info.

**Comment by yutannihilation** [comment]
Ahh, good catch... The error message indicates there's no `core` crate, which means you don't install the necessary target yet. That is `x86_64-windows-pc`.

Sorry, I forgot to write the installation step in the guide. I thought no one uses Windows except for me... :)

**Comment by daniellga** [comment]
I use it because of work :(. Yes, it would be very good to put it into the guide.
Thanks!
