### ISSUE TITLE
`ListSexp` example on guide

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#156]
If I understood correctly, `OwnedListSexp` should have it's `named` argument set to true for this example to work.

![image](https://github.com/yutannihilation/savvy/assets/43149605/e0e96d16-6aca-45d3-9071-a6f2604b28e3)

`OwnedListSexp's new() is different than other types; the second argument (named) indicates whether the list is named or unnamed. If false, the list doesn't have name and all operations on name like set_name() are simply ignored.`

**Comment by yutannihilation** [comment]
Thanks for catching, yes!
