### ISSUE TITLE
savvyed struct as an element of a List

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#162]
Returning a savvy created struct inside a list is returning the external pointer instead of the usual environment.

```
use savvy::{savvy, OwnedListSexp, OwnedStringSexp, Sexp};

#[savvy]
struct AAA {}

#[savvy]
impl AAA {
    fn new() -> savvy::Result<AAA> {
        Ok(AAA {})
    }
}

/// @export
#[savvy]
fn listunchecked() -> savvy::Result<Sexp> {
    let mut list = OwnedListSexp::new(1, false)?;
    let a = AAA {};
    list.set_value_unchecked(0, Sexp::try_from(a)?.0);
    list.into()
}

/// @export
#[savvy]
fn listchecked() -> savvy::Result<Sexp> {
    let mut list = OwnedListSexp::new(1, false)?;
    let a = AAA {};
    list.set_value(0, Sexp::try_from(a)?)?;
    list.into()
}

```

```
> a = listchecked()
> a
[[1]]
<pointer: 0x0000000000000001>

> b = listunchecked()
> b
[[1]]
<pointer: 0x0000000000000001>

> d = AAA$new()
> d
<environment: 0x0000027cf9d46a20>
attr(,"class")
[1] "AAA"
```

**Comment by yutannihilation** [comment]
Thanks for the report, but this is definitely the expected behavior. Savvy only wraps the outermost interface. If you want to put custom objects into it, it's your responsibility to wrap it nicely. I'd recommend to do it on R's side.

**Comment by daniellga** [comment]
Thanks! I will replace the list by my own savvy type. That should work.

**Comment by yutannihilation** [comment]
I see. Please feel free to file a new issue when you find some usage where this really need to be supported.

There are not strong, but small reasons I chose not to follow what extendr does:

* It constructs a method dynamically when it's called. I'm not sure if this is efficient or inefficient, but I feel environment is better in terms of tab-completion and simplicity. https://github.com/extendr/extendr/blob/1b6a5820866174cdebb9b729b2a4cbc94a1a4327/tests/extendrtests/R/extendr-wrappers.R#L155-L158
* I feel a bit uneasy to expose the external pointer to the user, though I don't come up with the case that the user immediately get in trouble with it.
