### ISSUE TITLE
Using #[savvy] on other files than lib.rs - GUIDE

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#211]
Can you give an example of this? I ask because I converted my package to use savvy and never needed to use `*`.

![image](https://github.com/yutannihilation/savvy/assets/43149605/90b85ed4-ec29-44b5-a09c-a8e17141e796)

**Comment by yutannihilation** [comment]
Wow, thanks for the finding! I don't know well how the symbols are exposed to C, but it seems there's no such distinction as public or private? I'll confirm.

**Comment by yutannihilation** [comment]
It turned out it's just that I didn't understand the Rust's visibility... Thanks for catching!
