### ISSUE TITLE
GetCurrentEnv?

### ISSUE THREAD

**Issue by eitsupi** [yutannihilation/savvy#253]
I wanted to do the following to get an R object from the Rust side, but since savvy currently only supports Global env (#82), is it possible to know the environment it was called from Rust?
https://github.com/duckdb/duckdb-r/blob/d18690cd642ceca238b54e43fbeffd6f340e45d4/src/register.cpp#L57-L64

**Comment by yutannihilation** [comment]
I intentionally do not implement support for environment. Could you show me any valid use case?

**Comment by eitsupi** [comment]
> Could you show me any valid use case?

Isn't it enough the way duckdb searches for an object by name in the link?

I would like to do the same thing here, but since we can only search the Global env, I cannot use DataFrames, etc. created inside functions. (To make matters worse, GlareDB currently does not have APIs for registering tables from the outside other way, such as `duckdb::duckdb_register()`.)
https://github.com/eitsupi/r-glaredb/blob/a951e7e9b8f47b0a8edf6bb94b95d571640200ba/src/rust/src/environment.rs#L12-L60

**Comment by eitsupi** [comment]
(Of course I understand that this is not currently being implemented intentionally, I simply wanted to point out that there could be situations where this would be necessary.)

**Comment by yutannihilation** [comment]
I simply cannot understand why it needs to search around in environments. It sounds like something should be done on R's side.

**Comment by yutannihilation** [comment]
Ah, never mind, now I think I understand.
