### ISSUE TITLE
Better error message for invalid type argument?

### ISSUE THREAD

**Issue by eitsupi** [yutannihilation/savvy#264]
If we currently pass the wrong type of argument to a function created with savvy, we don't know which argument type was incorrect because it does not show up in the error message.
It would be great if we could identify which function or argument is the cause.

``` r
prqlr::prql_compile(1, 1)
#> Error: Unexpected type: expected: character
#>   actual: double
```

<sup>Created on 2024-06-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment]
I think I can do better. What error message do you expect?

**Comment by eitsupi** [comment]
I was thinking that it would be nice if the Rust side argument name was added in the error message.

That is, since I believe the following function is used here

```rs
pub fn compile(
    prql_query: &str,
    target: &str,
    format: bool,
    signature_comment: bool,
) -> savvy::Result<Sexp> {
```

Like:

```r
#> Error: Unexpected type for the `prql_query` argument:
#>   expected: character
#>   actual: double
```

**Comment by eitsupi** [comment]
Awesome! Thanks for the quick update!
