### ISSUE TITLE
error: could not find native static library `unwind_protect`, perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#266]
Hi! I updated savvy and I am now getting this error. Do you happen to know what's the issue here?

![image](https://github.com/yutannihilation/savvy/assets/43149605/df25e272-6df7-49a8-9507-47384c2bd73a)

Cargo check works fine btw.

**Comment by daniellga** [comment]
with 0.6.4 it didn't work, so I tried with git version and it worked. I don't know what change made it work... Do you want me to close it anyway?

**Comment by yutannihilation** [comment]
Thanks for reporting. I forgot in what situation this happens, but I think `cargo clean` would have saved you because this is something related to build cache and nothing was changed between 0.6.4 and the current GitHub version.

**Comment by daniellga** [comment]
I did tons of cargo clean and it didn't work anyway :(
I will close it then. Thanks!

**Comment by yutannihilation** [comment]
Please feel free to file a new issue if you find the reproducible steps, thanks!
