### ISSUE TITLE
Replace `Rf_findVarInFrame` with `R_getVar`

### ISSUE THREAD

**Issue by yutannihilation** [yutannihilation/savvy#288]
At the time of https://github.com/yutannihilation/savvy/pull/274, there was no alternative. But, now it seems it has `R_getVar` now.

* https://cpp11.r-lib.org/news/index.html#r-non-api-related-changes-0-5-0
* https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Finding-and-setting-variables
* https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Some-API-replacements-for-non_002dAPI-entry-points

Note that, this is the first case when savvy needs a `cfg` for different R versions. I need to invent some mechanism first. Should I inject it in `build.rs`? Or, should it be a feature and set it in `Makevars`?

**Comment by shikokuchuo** [comment]
Seems  `R_GetVar()` / `R_GetVarEx()` is designed to be the equivalent to the R-level `get()` / `get0()` where the input is a character string.

For symbol lookup in an environment, I think the suggestion is just to use `Rf_eval(sym, env)`.

I've certainly not replaced any usage of `R_FindVarInFrame()` yet.

**Comment by yutannihilation** [comment]
Thanks for the information!

> For symbol lookup in an environment, I think the suggestion is just to use `Rf_eval(sym, env)`.

If I remember correctly, `Rf_eval()` always inherits, so the success of this evaluation doesn't mean the specified `sym` exists in the very `env`. That's why we tend to use `R_FindVarInFrame()`. (I've been away from R APIs for months, so I might be wrong)

**Comment by yutannihilation** [comment]
Ah, no, sorry, I confused it with `R_FindVarInFrame3()`. In savvy's case, you are absolutely right. Thanks!

**Comment by yutannihilation** [comment]
Oh, really? [The dev version of R-exts](https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Some-API-replacements-for-non_002dAPI-entry-points) says the replacements are the following. Does this help?

```
findVarInFrame3

    Use R_existsVarInFrame to test for existence. 

findVar
findVarInFrame

    Use R_getVar or R_getVarEx, added in R 4.5.0. In some cases using eval may suffice. 
```

**Comment by shikokuchuo** [comment]
Hmm sorry not sure where I got the idea the new versions take a character string... must have been reading the wrong function definition!

`R_getVarEx` seems to just be a wrapper around  `R_findVarInFrame` with some extra checks, so not too bad.

For my own purposes, as they are all on environments I construct, I've defined my own more efficient version of `Rf_FindVarInFrame()`.

**Comment by yutannihilation** [comment]
I chose to use `Rf_eval()` for the sake of implementational simplicity. Again, thanks for the hints!

https://github.com/yutannihilation/savvy/pull/292
