### ISSUE TITLE
[CLI] support raw identifiers?

### ISSUE THREAD

**Issue by eitsupi** [yutannihilation/savvy#289]
I noticed that if I use something like `r#struct` in the argument name, it is copied directly to the R file.

```rust
fn foo(r#struct: bool, ...)
```

```r
function(`r#struct`, ...
```

We could use underbars, etc. to get around the keywords, but it would be useful if savvy cli could support `r#` without copying it to other files.
(Similarly, reserved words as module names do not seem to be supported by savvy.)

**Comment by yutannihilation** [comment]
A bad news is that, even if savvy supports the raw identifiers, `struct` cannot be used as an identifier in C because it's a reserved keyword and C doesn't have such an escaping syntax like Rust and R. A good news is that, since C is in-between R and Rust and never face users directly, we can use arbitrary names for the signature. I'm still wondering if this is worth the effort, but I think this is possible.

**Comment by eitsupi** [comment]
Thanks for looking at this so quickly!
I was missing the perspective that it is a reserved keyword for C.

**Comment by yutannihilation** [comment]
I think this should work now. I quickly tried changing this line to `r#struct`, and it seems to work. Could you confirm? (CLI will be available soon as I'm releasing a new version...)

https://github.com/eitsupi/neo-r-polars/blob/bd9d94ab5a70dff83dcfa16899864bc918f0fa82/src/rust/src/series/export.rs#L53

**Comment by yutannihilation** [comment]
Here it is.

https://github.com/yutannihilation/savvy/releases/tag/v0.6.6

Note that, I don't address this part this time. Please let me know if you need this feature.

> (Similarly, reserved words as module names do not seem to be supported by savvy.)

**Comment by eitsupi** [comment]
Thanks for the quick update, that works great!
However, it seems that `r#` is not removed from the error message like ``Argument `r#struct` must be character``?
https://github.com/eitsupi/neo-r-polars/blob/6d6b720447c245438e5fb6be724674ed94c065fa/tests/testthat/test-series-to_r_vector.R#L93-L96

> Note that, I don't address this part this time. Please let me know if you need this feature.
> 
> > (Similarly, reserved words as module names do not seem to be supported by savvy.)

Yeah, I don't think this is a big problem. I was just surprised that the module was ignored without error when copying the following section previously.

https://github.com/pola-rs/polars/blob/6d4b79deefb0e29130d91a7cf3f65df1e9404c37/crates/polars-python/src/expr/mod.rs#L24
https://github.com/pola-rs/r-polars/blob/59e698c937973c72a08b69d46d8903f74ffba82c/src/rust/src/expr/mod.rs#L8

**Comment by yutannihilation** [comment]
Thanks for catching! Should be fixed on the main branch now.

**Comment by eitsupi** [comment]
Thanks for the update!
I confirm that the problem is completely resolved in 0.6.7-beta.1.
https://github.com/eitsupi/neo-r-polars/commit/b41b105da395fec4ca9761645019cc8cc83033c0

**Comment by yutannihilation** [comment]
Great! Thanks for confirming!
