### ISSUE TITLE
Update files without creating a new package

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#299]
Hi! I saw you changed some config, cleanup and makevars files in the last updates. I would like to update my package with these without using savvy init. Would it be enough to copy what is [here](https://github.com/yutannihilation/savvy/tree/main/R-package)? Or are some of these files platform specific?

**Comment by yutannihilation** [comment]
> Would it be enough to copy what is [here](https://github.com/yutannihilation/savvy/tree/main/R-package)?

Yeah, basically that's what you'll want to do. If you want to copy them, you'll also need to rename `src/Makevars.win` to `src/Makevars.win.in` as `configure.win` now generates it. Accordingly, you need to add it to `.gitignore`.

> Or are some of these files platform specific?

What do you mean? If you are talking about those files with or without `.win`, yes. If the question is whether or not the files of R package can defer depending the platform of the package developer, no.

**Comment by yutannihilation** [comment]
This should work.

https://github.com/daniellga/harmonium/pull/29

**Comment by daniellga** [comment]
I really meant different files generated for different systems. But you already answered anyway.
I was thinking of something like "savvy-cli reinit" to update these config, makevars, and related files automatically in an existing project but there's the downside of overwriting existing stuff, so the user should be aware of that. I don't know if it's a good idea, probably not.
Thanks for the PR!

**Comment by yutannihilation** [comment]
Basically, those files are what you are responsible for writing the contents. The template is just a template to be overwritten and customized. So, by its nature, it cannot be updated safely. I apologize that I couldn't figured out the best template earlier.
