### ISSUE TITLE
Using Rust in R projects without creating a package

### ISSUE THREAD

**Issue by fg-sempre** [yutannihilation/savvy#301]
I've been making several shiny apps using https://github.com/klmr/box to modularize the apps and avoid turning them into packages. If I just wanted to rewrite some parts of my apps using rust, I would need to have a separate rust project from my apps. I would like to know if in the future it would be possible to use savvy without having to create a package to inject some rust modules into my projects. I know it's possible to write functions like rust_function("fn add(a:f64, b:f64) -> f64 { a + b }") using rextendr, but this way it's not possible to use rust-analyzer for example.

**Comment by yutannihilation** [comment]
> I would like to know if in the future it would be possible to use savvy without having to create a package to inject some rust modules into my projects.

I think the answer is no.

Could you explain why you need to avoid creating a package? From you description, the main reason seems rust-analyzer?

**Comment by yutannihilation** [comment]
It seems I just don't understand what limitation box imposes. From these examples, it just allows you to use a package. What am I missing?

https://github.com/klmr/box?tab=readme-ov-file#loading-code

**Comment by fg-sempre** [comment]
> > I would like to know if in the future it would be possible to use savvy without having to create a package to inject some rust modules into my projects.
> 
> I think the answer is no.
> 
> Could you explain why you need to avoid creating a package? From you description, the main reason seems rust-analyzer?

Let's say I have a shiny app and I want to use a package I created locally using savvy, RcppArmadillo, pure R, etc. As far as I know, I need to install it in my app directly from my private repository on github. Using box, instead of this process, "my package" is simply an R file. For example:

```
./mod.R

#' @export
my_fn <- function() {...}
```

So, this avoids the whole process of creating a package locally, uploading it to github and installing it in my app. When I want to use the same functions in other apps, I simply copy and paste my module into the app and make some changes if necessary.

As far as I know, with box it is possible to use compiled code without the need to create a package (with code in c at least) https://klmr.me/box/articles/compiled-code.html

**Comment by fg-sempre** [comment]
> It seems I just don't understand what limitation box imposes. From these examples, it just allows you to use a package. What am I missing?
> 
> https://github.com/klmr/box?tab=readme-ov-file#loading-code

It's not a limitation, I didn't explain my problem properly.

**Comment by yutannihilation** [comment]
Thanks for the details. Hmm, sorry, then, I don't think I have enough energy to help you. As there's nothing I can do on savvy's side, let me close this issue.

Here's some hints. I think you are right in that you can use the compiled code as long as you have the pre-compiled DLL. You can load it via `dyn.load()`. You can just follow the instruction on the vignette. `R CMD SHLIB` should generate the DLL. In savvy R package, I use `pkgbuild::compile_dll()`, but it's basically the same thing as what the vignette says, iiuc.

https://github.com/yutannihilation/savvy-helper-R-package/blob/e532cad500ad96808ea7d6d930763e3f7375e553/R/source.R#L56-L67

You can also check what rextendr does in `rust_function()`.

Hope this helps a bit!

**Comment by fg-sempre** [comment]
Wonderful tips! It worked very well. Thanks!
