### ISSUE TITLE
Improve error msg for `#[savvy]` 

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#309]
I am having this error although I can't find at all where I am returning an `Infallible`. Is it possible to improve the error to point where it is? I have no other compilation errors apart from this one.

```
error[E0308]: mismatched types
   --> src/hresampler.rs:65:1
    |
65  | #[savvy]
    | ^^^^^^^^
    | |
    | expected `Error`, found `Infallible`
    | arguments to this function are incorrect
    |
note: function defined here
   --> /home/daniellga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/savvy-0.6.8/src/lib.rs:115:8
    |
115 | pub fn handle_error(e: crate::error::Error) -> SEXP {
    |        ^^^^^^^^^^^^
    = note: this error originates in the attribute macro `savvy` (in Nightly builds, run with -Z macro-backtrace for more info)
help: call `Into::into` on this expression to convert `Infallible` into `savvy::Error`
    |
65  | #[savvy].into()
    |         +++++++
```

**Comment by yutannihilation** [comment]
In my understanding, that's the compiler thing and there's nothing I can improve. Do you have any ideas?

I think you can temporarily remove `#[savvy]`.

**Comment by yutannihilation** [comment]
Can I see the actual code? `savvy::Error` implements `From<Infallible>`, so I'm wondering in what situation this compilation error can happen.

**Comment by daniellga** [comment]
It turns out I started redoing again all changes until that point where I got this error but I never got it again, even when replacing the new code with the old one. And I swear I did many cargo cleans in all this process. I simply don't know what happened. I thought in the proc macro implementation you could handle these kind of errors better, but I am not sure since I never had to implement one myself.

One thing I managed to test was that removing the savvy macro it would just compile normally.

Thanks for your help anyway.

**Comment by yutannihilation** [comment]
> I thought in the proc macro implementation you could handle these kind of errors better

A proc macro can catch only what can be known by static analysis on the given code. So, in general, type mismatch is difficult to catch. For example, if the mistake was that a wrong `Result` type is used as the return type, `#[savvy]` macro can detect it if it's explicitly qualified as `some_crate::Result`. But, if it's just `Result`, it cannot detect because there's no way to know which `Result` it comes from.

Anyway, glad to know you fixed the problem!
