### ISSUE TITLE
Sub-class of bundle classes

### ISSUE THREAD

**Issue by eitsupi** [yutannihilation/savvy#318]
Currently savvy exports a lot of functions like `$<-.StructName`, but I am thinking that by always setting up a subclass like `savvy_packagename_bundle`, we can reduce the number of things to export to one (`$<-.savvy_packagename_bundle`).
https://github.com/eitsupi/neo-r-polars/blob/af270bd8d0a9aff178d9324ab0327a71c468940e/NAMESPACE#L6-L25

**Comment by yutannihilation** [comment]
Sounds good. But, just curious, is this a problem?

> exports a lot of functions

**Comment by eitsupi** [comment]
No, I don't think it's a problem.
I just think it would make the codebase a bit simpler.

**Comment by yutannihilation** [comment]
Hm..., in my opinion, this would make the codebase of savvy a bit more complex instead of simpler. I think it's just a trade off.
But, let's do this. It's probably not a big deal anyway.

**Comment by eitsupi** [comment]
Thanks for implementing this!

> Hm..., in my opinion, this would make the codebase of savvy a bit more complex instead of simpler. I think it's just a trade off.

Oh, sorry. My intention was that a savvy based package would be simpler.

**Comment by yutannihilation** [comment]
Yeah, I meant it's the trade-off. Trade-off between savvy and savvy-based R package.
