### ISSUE TITLE
Error while compiling/using savvy

### ISSUE THREAD

**Issue by colinvwood** [yutannihilation/savvy#323]
I'm trying to install the R package [clarabel](https://cran.r-project.org/web/packages/clarabel/index.html). This gives me the following error: 

> The following warnings were emitted during compilation:
warning: savvy@0.6.4: x86_64-apple-darwin13.4: error: unsupported argument 'core2' to option '-march='
error: failed to run custom build command for `savvy v0.6.4`

I'm on an M-series Mac, inside of a conda environment (where all packages are built for x86_64 and then used with rosetta 2). Seems like something is being compiled for x86, but should be getting compiled for arm? Is there any way to intervene in this process with env variables or something? Apologies if this isn't the right place to post this issue; let me know if I should try to reach out to the clarabel developers instead. 

The full error log is attached. Thank you!

[log.txt](https://github.com/user-attachments/files/17561714/log.txt)

**Comment by eitsupi** [comment]
Will other packages based on savvy (`string2path`, `prqlr`) install successfully?
If so, is this a possible `clarabel`'s problem?

**Comment by yutannihilation** [comment]
> if I should try to reach out to the clarabel developers instead.

Yes, please do it first because I know nothing about the package. Please feel free to file a new issue here when it turned out it's something that savvy needs to address. Thanks!
