### ISSUE TITLE
config.toml is not tracked by default

### ISSUE THREAD

**Issue by paithiov909** [yutannihilation/savvy#326]
When I set up a new pacakge using `savvy::savvy_init()`, the `.cargo/config.toml` is ignored by `.gitignore`. But I suppose this is a file that should be tracked.

**Comment by yutannihilation** [comment]
Thanks for catching. I don't remember very well why it's ignored (probably I copied from extendr).

Do you get "hidden files and directories" NOTE if you remove the `.cargo` line in `.gitignore`?

**Comment by yutannihilation** [comment]
> Do you get "hidden files and directories" NOTE if you remove the `.cargo` line in `.gitignore`?

It seems this isn't the case.

https://github.com/yutannihilation/savvy/actions/runs/11831616221/job/32967057744?pr=327#step:8:73

**Comment by yutannihilation** [comment]
Should be fixed now. I'll release the new version in a day or so.

**Comment by paithiov909** [comment]
@yutannihilation
Thanks for early replies. Yes, I believe this issue was solved in #327.

By the way, I might have been noticed there is another issue.

> > Do you get "hidden files and directories" NOTE if you remove the `.cargo` line in `.gitignore`?
> 
> It seems this isn't the case.
> 
> https://github.com/yutannihilation/savvy/actions/runs/11831616221/job/32967057744?pr=327#step:8:73

This is because the generated `.Rbuildignore` ignores `^src/rust/.cargo$` directory, which came from [here](https://github.com/yutannihilation/savvy/blob/b73fd71ff2c6ba27f43a62358df6939aac88c925/savvy-cli/src/main.rs#L277-L293). And saddly, I got a "hidden files and directories" NOTE if removed this exclusion. 

If this is unintentional for you, it may need to be corrected as well.

**Comment by yutannihilation** [comment]
> This is because the generated .Rbuildignore ignores `^src/rust/.cargo$` directory, 

Ahh... Thanks, yes, unexpected. 

> it may need to be corrected as well.

The fix would be a bit complicated. `.cargo` directory needs to be created in `Makevars`, iirc, because it cannot be bundled directly. Let me think...

**Comment by yutannihilation** [comment]
Okay, I just remembered the original context. That `.cargo/config.toml` is needed only when you want to run `cargo test`, which I expect not so frequent.

> Currently, if a crate uses savvy, cargo test fails to compile even if the test code doesn't use the savvy API at all. This is because the symbols from Rinternals.h needs to be resolved.

* https://github.com/yutannihilation/savvy/pull/96
* https://github.com/yutannihilation/savvy/pull/98

So, it's fine to exclude it on building the package; the current status (exclude from `.gitignore` and include in `.Rbuildignore`) is the best. I'll improve the comments in `config.toml`. Thanks for catching anyway!
