### ISSUE TITLE
Can we read data from R's connection object?

### ISSUE THREAD

**Issue by eitsupi** [yutannihilation/savvy#328]
I know very little about how connection objects work, is there any way to manipulate them from Rust?
Context: pola-rs/r-polars#273

**Comment by yutannihilation** [comment]
Hmm, I too know very little. But, if I remember correctly, connection-related APIs were intentionally removed. So, I'm afraid it's impossible. I'll find some reference.

**Comment by yutannihilation** [comment]
I think this was the last news I saw about the connection API.

> Finally, it's worth noting that there's some lingering ill feelings over
how the connections API was treated. It was documented in R-exts only to be
later removed, including expunging mentions of it in the news.

https://stat.ethz.ch/pipermail/r-devel/2024-April/083356.html

**Comment by eitsupi** [comment]
Thanks for the quick reply!

Looking at this function of nanoarrow, perhaps there is a possibility to treat it like an external pointer?
https://github.com/apache/arrow-nanoarrow/blob/253b7ec0cb3cc4a5fb15c90c3879c2f2785d5600/r/R/ipc.R#L82-L110
https://github.com/apache/arrow-nanoarrow/blob/253b7ec0cb3cc4a5fb15c90c3879c2f2785d5600/r/src/ipc.c#L244-L265

**Comment by yutannihilation** [comment]
It seems you can call `readBin()` R function.

nanoarrow: https://github.com/apache/arrow-nanoarrow/blob/253b7ec0cb3cc4a5fb15c90c3879c2f2785d5600/r/R/ipc.R#L251-L258
readr: https://github.com/tidyverse/readr/blob/96ddac314b47402bc63e1f81c149c463cf58e3da/src/connection.h#L9

**Comment by eitsupi** [comment]
Thanks for pointing that out! It seems to be controllable from the current savvy API. I will give it a try.

**Comment by yutannihilation** [comment]
I think `FunctionSexp` can handle it, but please let me know if it doesn't work well.
