### ISSUE TITLE
CLI release workflow?

### ISSUE THREAD

**Issue by eitsupi** [yutannihilation/savvy#60]
Do you have any loyalty to cargo-dist?
Currently cargo-dist does not support cross compilation, so I don't think we can release binaries for arm64 Linux with our current workflow.

If I can completely rewrite CI and not have to use cargo-dist, I could release arm64 binaries for Linux.

**Comment by yutannihilation** [comment]
Thanks, but I'm not sure if I understand your problem.

This repository uses cargo-dist to provide the `savvy-cli` binary, which is for developing an R package that uses the savvy framework. The package users don't need the CLI. Do you mean you have to develop your R package on arm64 Linux? If so, I think you can either

* `cargo install savvy-cli` or
* use `xtask` that parses Rust code and generates the bindings

but neither of these works with the current savvy R package.

**Comment by eitsupi** [comment]
Thanks for the reply. Sorry, I misunderstood that the CLI is not in crates.io.
If that is the case, I can certainly use the source installation without any problems, but it would be useful to have a binary installation.

> neither of these works with the current savvy R package.

What this mean?

**Comment by yutannihilation** [comment]
I meant [the guidance in this repo's README](https://github.com/yutannihilation/savvy#create-a-new-r-package) doesn't work because it uses `savvy::savvy_init()` and `savvy::savvy_update()`, which internally downloads and runs savvy-cli.

Btw, it seems this part is not true today.

> Currently cargo-dist does not support cross compilation

[The changelog of v0.6.0](https://github.com/axodotdev/cargo-dist/blob/main/CHANGELOG.md#060-2023-12-18) says:

> We also now distribute aarch64 Linux binaries, which makes it easier to use cargo-dist to build software on aarch64 hosts.

Probably this should work. I'll try later.

``` toml
[package.metadata.dist]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
```

**Comment by yutannihilation** [comment]
It seems I'm missing something.

```
 error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-unknown-linux-gnu`
```
https://github.com/yutannihilation/savvy/actions/runs/7528420387/job/20490597787

**Comment by eitsupi** [comment]
> I meant [the guidance in this repo's README](https://github.com/yutannihilation/savvy#create-a-new-r-package) doesn't work because it uses `savvy::savvy_init()` and `savvy::savvy_update()`, which internally downloads and runs savvy-cli.

Oh, I understand.

> Probably this should work. I'll try later.

Looking at the cargo-dist repository, it assumes the use of the arm64 self-hosted runner (axodotdev/cargo-dist#638), which I believe still does not support cross-compilation.

**Comment by yutannihilation** [comment]
Got it. Thanks for the information.

**Comment by yutannihilation** [comment]
I decided to use BuildJet's custom runner.

https://github.com/yutannihilation/savvy/blob/34e77b08b4674f1bde4bc0cdc2d4162c12da7f41/Cargo.toml#L67-L69

Considering the following facts,

* They gives $5 credit for trial (c.f. https://buildjet.com/for-github-actions/docs/about/pricing)
* The cheapest runner costs $0.004 / minute
* It takes only 3 minutes to build the artifact

I can produce the binary for ARM64 Linux at least for a while. I'm not sure if I will keep paying when the trial is over, but anyway the binary for ARM64 Linux is available.

https://github.com/yutannihilation/savvy/releases/tag/v0.2.6

**Comment by eitsupi** [comment]
Awesome!
Feel free to close this issue, thanks!

**Comment by yutannihilation** [comment]
Thanks! I also updated the savvy R package, so `savvy::savvy_update()` should also work soon (not on R-universe yet).

https://github.com/yutannihilation/savvy-helper-R-package/commit/84186d9f77b89e07c80f2988f591b8d1eac63aeb

I don't have testing environment for ARM64 Linux, so please report if you find any problem. Anyway, let me close this for now!
